/** json-render $state paths for admin panels (load actions write, components read). */
export const ADMIN_STATE = {
  team: {
    users: "/admin/team/users",
    loading: "/admin/team/loading",
    error: "/admin/team/error",
  },
  routing: {
    pages: "/admin/routing/pages",
    currentPage: "/admin/routing/currentPage",
    loading: "/admin/routing/loading",
    error: "/admin/routing/error",
    treePages: "/admin/routing/tree/pages",
    treeStatus: "/admin/routing/tree/status",
    treeLoadedAt: "/admin/routing/tree/loadedAt",
    treeLoading: "/admin/routing/tree/loading",
    treeError: "/admin/routing/tree/error",
  },
  replay: {
    sessions: "/admin/replay/sessions",
    loading: "/admin/replay/loading",
    error: "/admin/replay/error",
    selectedSessionId: "/admin/replay/selectedSessionId",
    chunkPreview: "/admin/replay/chunkPreview",
    chunkLoading: "/admin/replay/chunkLoading",
    playerEvents: "/admin/replay/playerEvents",
    playerLoading: "/admin/replay/playerLoading",
  },
  flags: {
    flags: "/admin/flags/rows",
    loading: "/admin/flags/loading",
    error: "/admin/flags/error",
  },
  content: {
    loaded: "/admin/content/loaded",
    loading: "/admin/content/loading",
    error: "/admin/content/error",
    mediaAssets: "/admin/content/mediaAssets",
    mediaAssetsLoading: "/admin/content/mediaAssetsLoading",
  },
  layout: {
    loaded: "/admin/layout/loaded",
    loading: "/admin/layout/loading",
    error: "/admin/layout/error",
  },
  scope: {
    collections: "/admin/scope/collections",
    teams: "/admin/scope/teams",
    bindings: "/admin/scope/bindings",
    agentBindings: "/admin/scope/agentBindings",
    loading: "/admin/scope/loading",
    error: "/admin/scope/error",
  },
  analytics: {
    events: "/admin/analytics/events",
    aggregations: "/admin/analytics/aggregations",
    loading: "/admin/analytics/loading",
    error: "/admin/analytics/error",
  },
  traces: {
    traces: "/admin/traces/rows",
    loading: "/admin/traces/loading",
    error: "/admin/traces/error",
    selectedTraceId: "/admin/traces/selectedTraceId",
    detailSpans: "/admin/traces/detailSpans",
    detailLoading: "/admin/traces/detailLoading",
    detailError: "/admin/traces/detailError",
  },
  authSettings: {
    loaded: "/admin/auth/settings/loaded",
    loading: "/admin/auth/settings/loading",
    error: "/admin/auth/settings/error",
  },
  integrations: {
    llm: {
      loaded: "/admin/integrations/llm/loaded",
      loading: "/admin/integrations/llm/loading",
      error: "/admin/integrations/llm/error",
    },
    comms: {
      loaded: "/admin/integrations/comms/loaded",
      loading: "/admin/integrations/comms/loading",
      error: "/admin/integrations/comms/error",
    },
    oauth: {
      loaded: "/admin/integrations/oauth/loaded",
      loading: "/admin/integrations/oauth/loading",
      error: "/admin/integrations/oauth/error",
    },
    commsDeliveries: {
      loaded: "/admin/integrations/comms-deliveries/loaded",
      loading: "/admin/integrations/comms-deliveries/loading",
      error: "/admin/integrations/comms-deliveries/error",
    },
    webhooks: {
      loaded: "/admin/integrations/webhooks/loaded",
      loading: "/admin/integrations/webhooks/loading",
      error: "/admin/integrations/webhooks/error",
    },
    webhookDeliveries: {
      loaded: "/admin/integrations/webhook-deliveries/loaded",
      loading: "/admin/integrations/webhook-deliveries/loading",
      error: "/admin/integrations/webhook-deliveries/error",
    },
  },
  agents: {
    registry: "/admin/agents/registry",
    tasks: "/admin/agents/tasks",
    loading: "/admin/agents/loading",
    error: "/admin/agents/error",
    mintedToken: "/admin/agents/mintedToken",
    mintedTokenExpiresAt: "/admin/agents/mintedTokenExpiresAt",
    selectedTaskId: "/admin/agents/selectedTaskId",
    selectedTaskDetail: "/admin/agents/selectedTaskDetail",
  },
  loginBranding: {
    loaded: "/admin/auth/login-branding/loaded",
    loading: "/admin/auth/login-branding/loading",
    error: "/admin/auth/login-branding/error",
  },
} as const;
