name = "noname-edge"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
API_ORIGIN = "http://localhost:3000"
ZITADEL_ISSUER = "http://localhost:8080"
ZITADEL_CLIENT_ID = "383371862547169288"

[[kv_namespaces]]
binding = "KV"
id = "noname-edge-kv"

[[r2_buckets]]
binding = "R2"
bucket_name = "noname-assets"

[env.production]
API_ORIGIN = "https://api.noname.dev"
ZITADEL_ISSUER = "https://auth.noname.dev"

[[env.production.kv_namespaces]]
binding = "KV"
id = "noname-edge-kv-prod"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "noname-assets-prod"
