/** Admin catalog component types — excluded from storefront editor palette. */
export const ADMIN_PALETTE_EXCLUDED_TYPES = [
  "AdminShell",
  "AuthSettingsForm",
  "IntegrationsCommsForm",
  "IntegrationsLlmForm",
  "AgentsAdminForm",
  "LoginBrandingForm",
  "AccountSecurityForm",
  "UsersAdminForm",
  "FeatureFlagsAdmin",
  "SessionReplayAdmin",
  "AnalyticsEventsAdmin",
  "ScopeAdminForm",
  "ContentEntryAdmin",
  "LayoutEntryAdmin",
  "AdminHome",
  "PageTreeAdmin",
  "PageEntryAdmin",
] as const;
