import { z } from "zod";
import {
  catalogProps,
  documentFolderLabelsSchema,
  documentShareLabelsSchema,
  mediaFieldLabelsSchema,
  referenceFieldLabelsSchema,
} from "../../schemas/shared";
import { navItemConfigSchema } from "./shared";

const panelLabels = {
  title: z.string(),
  description: z.string().nullable(),
};

const adminShellLabels = {
  ...panelLabels,
  sidebarTitle: z.string(),
  productName: z.string(),
  settingsSectionLabel: z.string(),
  nav: z.record(z.string(), z.string()),
  settings: z.record(z.string(), z.string()),
  accountSecurity: z.string(),
  storefront: z.string(),
  signOut: z.string(),
  signIn: z.string(),
};

const adminShellConfig = {
  activeNav: z.string(),
  navItems: z.array(navItemConfigSchema),
  settingsItems: z.array(navItemConfigSchema),
  accountSecurityHref: z.string(),
  storefrontHref: z.string(),
};

/** Platform admin panels — settings, CMS, routing, team, flags, replay. */
export const adminComponentSchemas = {
  AdminShell: {
    props: catalogProps(adminShellLabels, adminShellConfig),
    slots: ["default"],
    description: "Admin dashboard shell with sidebar navigation",
  },
  AuthSettingsForm: {
    props: catalogProps(
      {
        ...panelLabels,
        saveLabel: z.string(),
        savingLabel: z.string(),
        loadingLabel: z.string(),
        successMessage: z.string(),
        socialProvidersLegend: z.string(),
        configuredBadgeLabel: z.string(),
        saveHelperText: z.string(),
        authProvidersLinkText: z.string(),
        allowPasswordLabel: z.string(),
        allowPasswordResetLabel: z.string(),
        allowSignUpLabel: z.string(),
        adminSecurityLegend: z.string(),
        requireMfaLabel: z.string(),
        mfaHelperText: z.string(),
        loginAppearanceLinkText: z.string(),
        googleLabel: z.string(),
        githubLabel: z.string(),
        appleLabel: z.string(),
        googleSecretPlaceholderNew: z.string(),
        googleSecretPlaceholderExisting: z.string(),
        githubSecretPlaceholderNew: z.string(),
        githubSecretPlaceholderExisting: z.string(),
        appleKeyPlaceholderNew: z.string(),
        appleKeyPlaceholderExisting: z.string(),
        forbiddenLabel: z.string(),
      },
      {},
    ),
    description: "Per-org auth provider toggles and ZITADEL IdP configuration",
  },
  IntegrationsCommsForm: {
    props: catalogProps(
      {
        ...panelLabels,
        loadingLabel: z.string(),
        forbiddenLabel: z.string(),
        providerLabel: z.string(),
        apiKeyLabel: z.string(),
        apiKeyPlaceholderNew: z.string(),
        apiKeyPlaceholderExisting: z.string(),
        configuredBadgeLabel: z.string(),
        fromEmailLabel: z.string(),
        fromNameLabel: z.string(),
        saveLabel: z.string(),
        savingLabel: z.string(),
        successMessage: z.string(),
      },
      {},
    ),
    description: "Per-org email provider and BYOK API key (Vault)",
  },
  IntegrationsLlmForm: {
    props: catalogProps(
      {
        ...panelLabels,
        loadingLabel: z.string(),
        forbiddenLabel: z.string(),
        providerLabel: z.string(),
        apiKeyLabel: z.string(),
        apiKeyPlaceholderNew: z.string(),
        apiKeyPlaceholderExisting: z.string(),
        configuredBadgeLabel: z.string(),
        allowPlatformFallbackLabel: z.string(),
        allowPlatformFallbackHelper: z.string(),
        saveLabel: z.string(),
        savingLabel: z.string(),
        successMessage: z.string(),
      },
      {},
    ),
    description: "Per-org LLM provider and BYOK API key (Vault)",
  },
  IntegrationsOAuthForm: {
    props: catalogProps(
      {
        ...panelLabels,
        loadingLabel: z.string(),
        forbiddenLabel: z.string(),
        connectLabel: z.string(),
        connectingLabel: z.string(),
        connectedLabel: z.string(),
        notConfiguredLabel: z.string(),
        emptyLabel: z.string(),
        refreshLabel: z.string(),
        connectionIdLabel: z.string(),
        providerLabel: z.string(),
      },
      {},
    ),
    description: "Connect third-party services via OAuth for this organization",
  },
  LoginBrandingForm: {
    props: catalogProps(
      {
        ...panelLabels,
        previewLoginLabel: z.string(),
        draftSavedMessage: z.string(),
        publishedMessage: z.string(),
        loadingLabel: z.string(),
        saveLabel: z.string(),
        savingLabel: z.string(),
        publishLabel: z.string(),
        publishingLabel: z.string(),
        forbiddenLabel: z.string(),
      },
      {
        segment: z.string(),
      },
    ),
    description: "Structured editor for login layout branding props",
  },
  AccountSecurityForm: {
    props: catalogProps(
      {
        title: z.string().default("Account security"),
        description: z
          .string()
          .nullable()
          .default("Set up an authenticator app for two-factor sign-in."),
        signInRequiredDescription: z.string(),
        signInLinkLabel: z.string(),
        backToStorefrontLabel: z.string(),
        enabledBadgeLabel: z.string(),
        enabledDescription: z.string(),
        checkingLabel: z.string(),
        mfaRequiredAlert: z.string(),
        idleDescription: z.string(),
        idleButtonLabel: z.string(),
        idleButtonPendingLabel: z.string(),
        setupDescription: z.string(),
        qrAltText: z.string(),
        verificationCodeLabel: z.string(),
        verificationCodePlaceholder: z.string(),
        confirmSetupLabel: z.string(),
        confirmSetupPendingLabel: z.string(),
        enabledStepDescription: z.string(),
        continueToAdminLabel: z.string(),
      },
      {
        variant: z.enum(["admin", "standalone"]).default("standalone"),
      },
    ),
    description: "TOTP enrollment for the signed-in user",
  },
  UsersAdminForm: {
    props: catalogProps(
      {
        ...panelLabels,
        loadingLabel: z.string(),
        inviteSectionTitle: z.string(),
        inviteSectionDescription: z.string(),
        inviteLabel: z.string(),
        invitingLabel: z.string(),
        inviteSuccessMessage: z.string(),
        roleUpdatedMessage: z.string(),
        emptyTableMessage: z.string(),
        emailColumnHeader: z.string(),
        roleColumnHeader: z.string(),
        mfaColumnHeader: z.string(),
        statusColumnHeader: z.string(),
        mfaEnabledLabel: z.string(),
        mfaOffLabel: z.string(),
        forbiddenLabel: z.string(),
      },
      {},
    ),
    description: "List and invite ZITADEL users for this org",
  },
  AgentsAdminForm: {
    props: catalogProps(
      {
        ...panelLabels,
        loadingLabel: z.string(),
        forbiddenLabel: z.string(),
        registrySectionTitle: z.string(),
        registrySectionDescription: z.string(),
        slugLabel: z.string(),
        labelLabel: z.string(),
        registerLabel: z.string(),
        registeringLabel: z.string(),
        registerSuccessMessage: z.string(),
        deleteLabel: z.string(),
        deleteConfirm: z.string(),
        deleteSuccessMessage: z.string(),
        mintTokenLabel: z.string(),
        mintingLabel: z.string(),
        mintSuccessMessage: z.string(),
        tokenExpiresLabel: z.string(),
        grantFolderLabel: z.string(),
        grantFolderSuccessMessage: z.string(),
        folderSelectLabel: z.string(),
        emptyRegistryMessage: z.string(),
        tasksSectionTitle: z.string(),
        tasksSectionDescription: z.string(),
        emptyTasksMessage: z.string(),
        approveLabel: z.string(),
        rejectLabel: z.string(),
        taskApprovedMessage: z.string(),
        taskRejectedMessage: z.string(),
        slugColumnHeader: z.string(),
        labelColumnHeader: z.string(),
        ownerColumnHeader: z.string(),
        statusColumnHeader: z.string(),
        typeColumnHeader: z.string(),
        promptColumnHeader: z.string(),
        reviewedByColumnHeader: z.string(),
        tasksForbiddenLabel: z.string(),
      },
      {},
    ),
    description: "Register agents, mint tokens, grant folder access, review tasks",
  },
  ScopeAdminForm: {
    props: catalogProps(
      {
        ...panelLabels,
        loadingLabel: z.string(),
        folderLabel: z.string(),
        folderPlaceholder: z.string(),
        folderSelectLabel: z.string(),
        teamLabel: z.string(),
        teamPlaceholder: z.string(),
        teamSelectLabel: z.string(),
        createFolderLabel: z.string(),
        creatingFolderLabel: z.string(),
        createTeamLabel: z.string(),
        creatingTeamLabel: z.string(),
        bindingLabel: z.string(),
        editAccessLabel: z.string(),
        publishAccessLabel: z.string(),
        accessOnLabel: z.string(),
        accessOffLabel: z.string(),
        bindingsListTitle: z.string(),
        emptyBindingsMessage: z.string(),
        deleteFolderLabel: z.string(),
        deleteTeamLabel: z.string(),
        deletingLabel: z.string(),
        deleteSuccessMessage: z.string(),
        deleteFolderConfirm: z.string(),
        deleteTeamConfirm: z.string(),
        userLabel: z.string(),
        memberSearchPlaceholder: z.string(),
        noMemberMatchesMessage: z.string(),
        memberNoneSelectedLabel: z.string(),
        memberSelectedLabel: z.string(),
        clearSelectionLabel: z.string(),
        membersListTitle: z.string(),
        emptyMembersMessage: z.string(),
        memberNameColumnHeader: z.string(),
        orgRoleColumnHeader: z.string(),
        onTeamColumnHeader: z.string(),
        slotEditorLabel: z.string(),
        slotPublisherLabel: z.string(),
        removeEditorLabel: z.string(),
        removePublisherLabel: z.string(),
        grantOnePersonLabel: z.string(),
        grantManyPeopleLabel: z.string(),
        grantingLabel: z.string(),
        revokeLabel: z.string(),
        revokingLabel: z.string(),
        grantSuccessMessage: z.string(),
        revokeSuccessMessage: z.string(),
        foldersSectionTitle: z.string(),
        foldersSectionHint: z.string(),
        teamsSectionTitle: z.string(),
        teamsSectionHint: z.string(),
        bindingsSectionTitle: z.string(),
        bindingsSectionHint: z.string(),
        agentLabel: z.string(),
        agentBindingsListTitle: z.string(),
        emptyAgentBindingsMessage: z.string(),
        removeAgentBindingLabel: z.string(),
        membershipSectionTitle: z.string(),
        membershipSectionHint: z.string(),
        emptyFoldersMessage: z.string(),
        emptyTeamsMessage: z.string(),
        helpText: z.string(),
        forbiddenLabel: z.string(),
      },
      {},
    ),
    description: "Manage content folders, teams, and folder access",
  },
  FeatureFlagsAdmin: {
    props: catalogProps(
      {
        ...panelLabels,
        loadingLabel: z.string(),
        empty: z.string(),
        onLabel: z.string(),
        offLabel: z.string(),
        togglingLabel: z.string(),
        forbiddenLabel: z.string(),
      },
      {},
    ),
    description: "List and toggle feature flags for this org",
  },
  AnalyticsEventsAdmin: {
    props: catalogProps(
      {
        ...panelLabels,
        loadingLabel: z.string(),
        emptyEvents: z.string(),
        emptyAggregations: z.string(),
        refreshLabel: z.string(),
        refreshingLabel: z.string(),
        forbiddenLabel: z.string(),
        aggregationsTitle: z.string(),
        aggregationsDescription: z.string().nullable(),
        eventsTitle: z.string(),
        eventsDescription: z.string().nullable(),
        eventTypeColumnHeader: z.string(),
        countColumnHeader: z.string(),
        timestampColumnHeader: z.string(),
        sourceColumnHeader: z.string(),
        sessionColumnHeader: z.string(),
        schemaColumnHeader: z.string(),
      },
      {},
    ),
    description: "Browse analytics events and aggregations for this org",
  },
  SessionReplayAdmin: {
    props: catalogProps(
      {
        ...panelLabels,
        loadingLabel: z.string(),
        empty: z.string(),
        sessionColumnHeader: z.string(),
        chunksColumnHeader: z.string(),
        lastSeenColumnHeader: z.string(),
        previewTitle: z.string(),
        previewLoadingLabel: z.string(),
        loadChunkLabel: z.string(),
        playSessionLabel: z.string(),
        playerLoadingLabel: z.string(),
        forbiddenLabel: z.string(),
        noChunksLabel: z.string(),
      },
      {},
    ),
    description: "List session replay chunks for this org (admin only)",
  },
  ContentEntryAdmin: {
    props: catalogProps(
      {
        ...panelLabels,
        deleteLabel: z.string(),
        deletingLabel: z.string(),
        createDraftLabel: z.string(),
        creatingLabel: z.string(),
        loadingLabel: z.string(),
        entryCreatedMessage: z.string(),
        entrySavedMessage: z.string(),
        entryPublishedMessage: z.string(),
        entryDeletedMessage: z.string(),
        deleteConfirmMessage: z.string(),
        saveLabel: z.string(),
        savingLabel: z.string(),
        publishLabel: z.string(),
        publishingLabel: z.string(),
        ...mediaFieldLabelsSchema.shape,
        ...referenceFieldLabelsSchema.shape,
        ...documentFolderLabelsSchema.shape,
        ...documentShareLabelsSchema.shape,
      },
      {
        locale: z.string(),
      },
    ),
    description: "Generic CMS entry list and form driven by content type schema",
  },
  LayoutEntryAdmin: {
    props: catalogProps(
      {
        ...panelLabels,
        loadingLabel: z.string(),
        draftSavedMessage: z.string(),
        publishedMessage: z.string(),
        saveLabel: z.string(),
        savingLabel: z.string(),
        publishLabel: z.string(),
        publishingLabel: z.string(),
        allLayoutsLinkLabel: z.string(),
        contentRefLabel: z.string(),
        contentRefPlaceholder: z.string(),
        contentRefHint: z.string(),
        specJsonLabel: z.string(),
        templateMetaTemplateLabel: z.string(),
        templateMetaSegmentLabel: z.string(),
        templateMetaStatusLabel: z.string(),
        metaSeparator: z.string(),
        emptyLayoutsMessage: z.string(),
        templateColumnHeader: z.string(),
        statusColumnHeader: z.string(),
        contentRefColumnHeader: z.string(),
        hasContentRefYes: z.string(),
        templateNotFoundPrefix: z.string(),
        templateNotFoundSuffix: z.string(),
        ...documentFolderLabelsSchema.shape,
        ...documentShareLabelsSchema.shape,
      },
      {
        segment: z.string(),
      },
    ),
    description: "Layout template list and JSON spec editor with publish",
  },
  AdminHome: {
    props: catalogProps(
      {
        ...panelLabels,
        links: z.record(
          z.string(),
          z.object({
            label: z.string(),
            description: z.string(),
          }),
        ),
      },
      {
        links: z.array(
          z.object({
            id: z.string(),
            href: z.string(),
          }),
        ),
      },
    ),
    description: "Admin overview with links to platform settings",
  },
  PageTreeAdmin: {
    props: catalogProps(
      {
        ...panelLabels,
        saveTreeLabel: z.string(),
        savingTreeLabel: z.string(),
        treeSavedMessage: z.string(),
        addEntryLabel: z.string(),
        removeEntryLabel: z.string(),
        pageDocumentsLinkLabel: z.string(),
        treeLoadingLabel: z.string(),
      },
      {
        locale: z.string(),
      },
    ),
    description: "Edit page_tree slug → pageId mappings",
  },
  PageEntryAdmin: {
    props: catalogProps(
      {
        ...panelLabels,
        saveLabel: z.string(),
        savingLabel: z.string(),
        pageSavedMessage: z.string(),
        createLabel: z.string(),
        creatingLabel: z.string(),
        loadingLabel: z.string(),
        editUrlTreeLabel: z.string(),
        allPagesLinkLabel: z.string(),
        urlTreeLinkLabel: z.string(),
        pageKeyLabel: z.string(),
        statusSeparator: z.string(),
        layoutRefLabel: z.string(),
        layoutRefPlaceholder: z.string(),
        contentRefLabel: z.string(),
        contentRefPlaceholder: z.string(),
        contentRefHint: z.string(),
        newPageTitle: z.string(),
        newPageDescription: z.string(),
        newPageKeyLabel: z.string(),
        newPageKeyPlaceholder: z.string(),
        emptyListMessage: z.string(),
        pageKeyColumnHeader: z.string(),
        layoutColumnHeader: z.string(),
        contentRefColumnHeader: z.string(),
        statusColumnHeader: z.string(),
        pageNotFoundPrefix: z.string(),
        pageNotFoundSuffix: z.string(),
      },
      {},
    ),
    description: "Edit routing page documents (layoutRef, contentRef)",
  },
};

export {
  draftPublishLabelsSchema,
  mediaFieldLabelsSchema,
  referenceFieldLabelsSchema,
} from "../../schemas/shared";
